#!/bin/bash
set -euo pipefail
exec > >(tee /var/log/penumbra-init.log | logger -t penumbra-init) 2>&1

echo "=== Penumbra instance bootstrap ==="
AWS_REGION="${aws_region}"
ECR_REGISTRY="${ecr_registry}"
ECR_REPO="${ecr_repo}"
LOG_GROUP="${log_group}"
APP_DIR="/opt/penumbra"
DATA_DIR="/data"

# ── 1. System packages ──────────────────────────────────────────────────────
dnf update -y
dnf install -y docker awscli2

systemctl enable docker
systemctl start docker

# ── 2. Mount EBS data volume ────────────────────────────────────────────────
# Device may appear as /dev/xvdf or /dev/nvme1n1 depending on instance type
DATA_DEV=""
for d in /dev/xvdf /dev/nvme1n1; do
  if [ -b "$d" ]; then
    DATA_DEV="$d"
    break
  fi
done

if [ -z "$DATA_DEV" ]; then
  echo "WARNING: data volume not found — DuckDB will use root volume"
  mkdir -p "$DATA_DIR"
else
  # Format only if no filesystem exists (new volume)
  if ! blkid "$DATA_DEV" > /dev/null 2>&1; then
    echo "Formatting data volume $DATA_DEV"
    mkfs.ext4 "$DATA_DEV"
  fi

  mkdir -p "$DATA_DIR"
  mount "$DATA_DEV" "$DATA_DIR"

  # Persist mount across reboots
  DATA_UUID=$(blkid -s UUID -o value "$DATA_DEV")
  if ! grep -q "$DATA_UUID" /etc/fstab; then
    echo "UUID=$DATA_UUID  $DATA_DIR  ext4  defaults,nofail  0  2" >> /etc/fstab
  fi
fi

mkdir -p "$DATA_DIR/penumbra"

# ── 3. Fetch secrets from SSM Parameter Store ───────────────────────────────
echo "Fetching secrets from SSM..."
mkdir -p "$APP_DIR"

fetch_param() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "/penumbra/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>/dev/null || echo ""
}

cat > "$APP_DIR/.env" <<EOF
# Generated by user-data — do not edit manually (re-runs overwrite this)
POLYMARKET_PRIVATE_KEY=$(fetch_param polymarket_private_key)
POLYMARKET_API_KEY=$(fetch_param polymarket_api_key)
POLYMARKET_API_SECRET=$(fetch_param polymarket_api_secret)
POLYMARKET_API_PASSPHRASE=$(fetch_param polymarket_api_passphrase)

TAVILY_API_KEY=$(fetch_param tavily_api_key)
ALCHEMY_API_KEY=$(fetch_param alchemy_api_key)
ALCHEMY_POLYGON_URL=https://polygon-mainnet.g.alchemy.com/v2/$(fetch_param alchemy_api_key)

AWS_REGION=$AWS_REGION

DUCKDB_PATH=/app/data/sentinel.duckdb

JUDGE_MAX_WORKERS=4
BEDROCK_TIER1_DAILY_LIMIT=5000
BEDROCK_TIER2_DAILY_LIMIT=0
NEWS_MIN_SCORE=70
ALERT_MIN_SCORE=80
SIGNAL_MIN_SCORE=30
ZSCORE_THRESHOLD=3.5
MIN_TRADE_SIZE_USD=500

API_HOST=0.0.0.0
API_PORT=8000
DASHBOARD_ORIGIN=*

LOG_LEVEL=INFO
LOG_FORMAT=json
EOF

chmod 600 "$APP_DIR/.env"

# ── 4. Write docker-compose.yml ─────────────────────────────────────────────
cat > "$APP_DIR/docker-compose.yml" <<EOF
services:
  sentinel:
    image: $ECR_REGISTRY/$ECR_REPO:latest
    env_file: $APP_DIR/.env
    ports:
      - "8000:8000"
    volumes:
      - $DATA_DIR/penumbra:/app/data
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-region: $AWS_REGION
        awslogs-group: $LOG_GROUP
        awslogs-stream: sentinel
        awslogs-create-group: "false"
EOF

# ── 5. Write deploy script (called by GitHub Actions via SSM) ───────────────
cat > "$APP_DIR/deploy.sh" <<'DEPLOY'
#!/bin/bash
set -euo pipefail
exec >> /var/log/penumbra-deploy.log 2>&1
echo "=== Deploy triggered at $(date) ==="

APP_DIR="/opt/penumbra"
AWS_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
ECR_REGISTRY=$(aws ecr describe-repositories \
  --repository-names penumbra \
  --region "$AWS_REGION" \
  --query 'repositories[0].repositoryUri' \
  --output text | sed 's|/penumbra||')

# Login to ECR
aws ecr get-login-password --region "$AWS_REGION" \
  | docker login --username AWS --password-stdin "$ECR_REGISTRY"

# Pull latest image and restart
cd "$APP_DIR"
docker compose pull
docker compose up -d

echo "=== Deploy complete at $(date) ==="
DEPLOY
chmod +x "$APP_DIR/deploy.sh"

# ── 6. Write secret-refresh script (run manually after rotating keys) ────────
cat > "$APP_DIR/refresh-secrets.sh" <<'REFRESH'
#!/bin/bash
set -euo pipefail
echo "Refreshing secrets from SSM Parameter Store..."

APP_DIR="/opt/penumbra"
AWS_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)

fetch_param() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "/penumbra/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>/dev/null || echo ""
}

ALCHEMY_KEY=$(fetch_param alchemy_api_key)

cat > "$APP_DIR/.env" <<EOF
POLYMARKET_PRIVATE_KEY=$(fetch_param polymarket_private_key)
POLYMARKET_API_KEY=$(fetch_param polymarket_api_key)
POLYMARKET_API_SECRET=$(fetch_param polymarket_api_secret)
POLYMARKET_API_PASSPHRASE=$(fetch_param polymarket_api_passphrase)

TAVILY_API_KEY=$(fetch_param tavily_api_key)
ALCHEMY_API_KEY=$ALCHEMY_KEY
ALCHEMY_POLYGON_URL=https://polygon-mainnet.g.alchemy.com/v2/$ALCHEMY_KEY

AWS_REGION=$AWS_REGION

DUCKDB_PATH=/app/data/sentinel.duckdb

JUDGE_MAX_WORKERS=4
BEDROCK_TIER1_DAILY_LIMIT=5000
BEDROCK_TIER2_DAILY_LIMIT=0
NEWS_MIN_SCORE=70
ALERT_MIN_SCORE=80
SIGNAL_MIN_SCORE=30
ZSCORE_THRESHOLD=3.5
MIN_TRADE_SIZE_USD=500

API_HOST=0.0.0.0
API_PORT=8000
DASHBOARD_ORIGIN=*

LOG_LEVEL=INFO
LOG_FORMAT=json
EOF

chmod 600 "$APP_DIR/.env"
echo "Done. Restart container to pick up new values: cd $APP_DIR && docker compose restart"
REFRESH
chmod +x "$APP_DIR/refresh-secrets.sh"

# ── 7. Pull image and start container ───────────────────────────────────────
echo "Logging in to ECR..."
aws ecr get-login-password --region "$AWS_REGION" \
  | docker login --username AWS --password-stdin "$ECR_REGISTRY"

echo "Pulling image..."
# The image may not exist yet on first boot (before the first CI deploy).
# Pull if available, skip gracefully if not.
if aws ecr describe-images \
    --repository-name "$ECR_REPO" \
    --region "$AWS_REGION" \
    --query 'imageDetails[0]' \
    --output text > /dev/null 2>&1; then
  docker pull "$ECR_REGISTRY/$ECR_REPO:latest"
  cd "$APP_DIR"
  docker compose up -d
  echo "Container started."
else
  echo "No image in ECR yet — container will start after first CI deploy."
fi

echo "=== Bootstrap complete ==="
